[package]
name = "nomad"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.2"
bevy_flycam = "0.14.1"
bevy_rapier3d = { version = "0.27.0", features = ["enhanced-determinism"] }

[profile.dev.package."*"]
opt-level = 3
